language: php
matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true
branches:
  only:
    master
install:
  - if [[ $TRAVIS_PHP_VERSION > '7.1' || $TRAVIS_PHP_VERSION = nightly ]]; then wget -O ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-7.phar; fi
  - if [[ $TRAVIS_PHP_VERSION > '7.1' || $TRAVIS_PHP_VERSION = nightly ]]; then chmod 755 ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit; fi
before_script:
  - cp _test/mysql.conf.php.dist _test/mysql.conf.php
  - cp _test/pgsql.conf.php.dist _test/pgsql.conf.php
  - php -v
  - phpunit --version
script: vendor/bin/phpunit --bootstrap vendor/autoload.php tests
